#!/bin/bash

echo "Installing..."
echo "  Adding templatedir git config..."
git config --global init.templatedir ~/.git-templates
echo "  Making directory..."
mkdir -p ~/.git-templates/hooks
echo "  Copying hook to directory..."
cp prepare-commit-msg  ~/.git-templates/hooks/
echo "  Making hook executable..."
chmod a+x ~/.git-templates/hooks/prepare-commit-msg

echo -e "\nIn the root of your repository, type `git init` to reinitialize with the prepare commit msg hook."
